### ISSUE TITLE
Support binary distribution

### ISSUE THREAD

**Issue by bmf-san** [bmf-san/ggc#18]

**Comment by thatonecodes** [comment]
We could use [GoReleaser](https://goreleaser.com/) so it's easy to build binaries across platforms by just tagging the release. We could also think about setting up automated tests and checks before releases.

```yaml
# .goreleaser.yml
builds:
  - main: ./cmd/ggc/main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

release:
  github:
    owner: bmf-san
    name: ggc

checksum:
  name_template: "checksums.txt"
```
And add something like this to the gh workflows:
```yaml
# .github/workflows/release.yml
name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
